<?xml version="1.0" encoding="utf-8"?><Database Name="MiniWotc" Class="eWotcDB" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=.\SQLExpress;Initial Catalog=MiniWotc;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="MiniWotcConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Companies" Member="Companies">
    <Type Name="Company">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(200) NOT NULL" CanBeNull="false" />
      <Association Name="Company_Location" Member="Locations" ThisKey="ID" OtherKey="CompanyId" Type="Location" />
    </Type>
  </Table>
  <Table Name="dbo.Locations" Member="Locations">
    <Type Name="Location">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="CompanyId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Address" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="City" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="State" Type="System.String" DbType="VarChar(2) NOT NULL" CanBeNull="false" />
      <Association Name="Location_Employee" Member="Employees" ThisKey="ID" OtherKey="LocationId" Type="Employee" />
      <Association Name="Company_Location" Member="Company" ThisKey="CompanyId" OtherKey="ID" Type="Company" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Employees" Member="Employees">
    <Type Name="Employee">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="SSN" Type="System.String" DbType="VarChar(9)" CanBeNull="true" />
      <Column Name="Name" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Address" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="LocationId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="City" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="State" Type="System.String" DbType="VarChar(2) NOT NULL" CanBeNull="false" />
      <Column Name="QualifiedTargetGroup" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CertifiedTargetGroupId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Employee_EmployeeDocument" Member="EmployeeDocuments" ThisKey="ID" OtherKey="EmployeeId" Type="EmployeeDocument" />
      <Association Name="Location_Employee" Member="Location" ThisKey="LocationId" OtherKey="ID" Type="Location" IsForeignKey="true" />
      <Association Name="TargetGroup_Employee" Member="TargetGroup" ThisKey="CertifiedTargetGroupId" OtherKey="ID" Type="TargetGroup" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.EmployeeDocuments" Member="EmployeeDocuments">
    <Type Name="EmployeeDocument">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="EmployeeId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DocumentId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ReceivedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="Employee_EmployeeDocument" Member="Employee" ThisKey="EmployeeId" OtherKey="ID" Type="Employee" IsForeignKey="true" />
      <Association Name="Document_EmployeeDocument" Member="Document" ThisKey="DocumentId" OtherKey="ID" Type="Document" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Documents" Member="Documents">
    <Type Name="Document">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Document" Member="Document1" Type="System.String" DbType="VarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="AllowedDays" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Document_EmployeeDocument" Member="EmployeeDocuments" ThisKey="ID" OtherKey="DocumentId" Type="EmployeeDocument" />
    </Type>
  </Table>
  <Table Name="dbo.TargetGroups" Member="TargetGroups">
    <Type Name="TargetGroup">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TargetGroup" Member="TargetGroup1" Type="System.String" DbType="VarChar(2) NOT NULL" CanBeNull="false" />
      <Column Name="TargetGroupCode" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Description" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="MaxCredit" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Association Name="TargetGroup_Employee" Member="Employees" ThisKey="ID" OtherKey="CertifiedTargetGroupId" Type="Employee" />
    </Type>
  </Table>
</Database>